- name: Build three-tier-app inventory
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Get openstack servers
    os_server_info:
      cloud: ospcloud
    register: r_os_server_info
  - debug:
      var: r_os_server_info
#  - name: Add hosts
#    add_host:
#      name: "{{ item.name }}"
#      groups: "{{ item.metadata.group }}"
#      ansible_host: "{{ item.public_v4 }}"
#      ansible_user: cloud-user
#      ansible_ssh_private_key_file: ~/.ssh/test_id_rsa
#      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#    loop: "{{ r_os_server_info.openstack_servers }}"
#    loop_control:
#      label: "{{ item.name }}"

#- import_playbook: main.yml
